//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public ANSWER()
        {
            this.KOMENTAR = new HashSet<KOMENTAR>();
            this.REPORT = new HashSet<REPORT>();
        }
    
        public int ID_ANSWER { get; set; }
        public Nullable<int> ID_QUESTION { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string POST_KOMENT { get; set; }
        public Nullable<System.DateTime> TGGL_ANSWER { get; set; }
        public Nullable<int> CLAP_ANSWER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<KOMENTAR> KOMENTAR { get; set; }
        public virtual ICollection<REPORT> REPORT { get; set; }
    }
}
