//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOMENTAR
    {
        public KOMENTAR()
        {
            this.REPORT = new HashSet<REPORT>();
        }
    
        public int ID_KOMEN { get; set; }
        public Nullable<int> ID_SHARING { get; set; }
        public Nullable<int> ID_ANSWER { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string POST_KOMEN { get; set; }
        public Nullable<System.DateTime> TGL_KOMEN { get; set; }
        public Nullable<int> CLAP_KOMENTAR { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual ANSWER ANSWER { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<REPORT> REPORT { get; set; }
        public virtual SHARING SHARING { get; set; }
    }
}
