//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public QUESTION()
        {
            this.ANSWER = new HashSet<ANSWER>();
            this.TAGS_QUESTION = new HashSet<TAGS_QUESTION>();
        }
    
        public int ID_QUESTION { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string TITLE_QUESTION { get; set; }
        public string POSTING { get; set; }
        public Nullable<System.DateTime> TGGL_QUESTION { get; set; }
        public Nullable<int> CLAP_QUESTION { get; set; }
        public Nullable<System.DateTime> UDATE_DATE { get; set; }
    
        public virtual ICollection<ANSWER> ANSWER { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<TAGS_QUESTION> TAGS_QUESTION { get; set; }
    }
}
