//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public int ID_REPORT { get; set; }
        public Nullable<int> ID_KOMEN { get; set; }
        public Nullable<int> ID_ANSWER { get; set; }
        public Nullable<int> ID_KATEGORY { get; set; }
    
        public virtual ANSWER ANSWER { get; set; }
        public virtual KATEGORY_REPORT KATEGORY_REPORT { get; set; }
        public virtual KOMENTAR KOMENTAR { get; set; }
    }
}
