//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHARING
    {
        public SHARING()
        {
            this.KOMENTAR = new HashSet<KOMENTAR>();
            this.TAGS_SHARING = new HashSet<TAGS_SHARING>();
        }
    
        public int ID_SHARING { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> ID_TAGS { get; set; }
        public string TITLE_SHARING { get; set; }
        public string POSTTING { get; set; }
        public Nullable<System.DateTime> TGGL_SHARE { get; set; }
        public string UPLOAD_FILE { get; set; }
        public Nullable<int> CLAP_SHARING { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual ICollection<KOMENTAR> KOMENTAR { get; set; }
        public virtual TAGS TAGS { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<TAGS_SHARING> TAGS_SHARING { get; set; }
    }
}
