//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.USER = new HashSet<USER>();
        }
    
        public int ID_STATUS { get; set; }
        public string NAMA_STATUS { get; set; }
    
        public virtual ICollection<USER> USER { get; set; }
    }
}
