//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.ANSWER = new HashSet<ANSWER>();
            this.KOMENTAR = new HashSet<KOMENTAR>();
            this.QUESTION = new HashSet<QUESTION>();
            this.SHARING = new HashSet<SHARING>();
        }
    
        public int ID_USER { get; set; }
        public Nullable<int> STA_ID_STATUS { get; set; }
        public Nullable<int> ID_LV { get; set; }
        public string NAMA { get; set; }
        public string Alamat { get; set; }
        public byte[] FOTO_PROFILE { get; set; }
        public Nullable<int> RATING { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<ANSWER> ANSWER { get; set; }
        public virtual ICollection<KOMENTAR> KOMENTAR { get; set; }
        public virtual LEVEL_USER LEVEL_USER { get; set; }
        public virtual ICollection<QUESTION> QUESTION { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual ICollection<SHARING> SHARING { get; set; }
    }
}
